version: "3.4"

services:
  nlp-natasha:
    user: 1000:1000 # for linux to delete created files
    image: nlp-natasha
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
    restart: always
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8000",
      ]
    ports:
      - 8000:8000
      - 5678:5678
