version: '3.4'

services:
  nlp-natasha:
    image: nlp-natasha
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:  
      - 8000:8000

  pullenti-server:
    image: pullenti/pullenti-server
    ports:
      - 8080:8080
